from enum import Enum


class IATIFileTypes(Enum):
    """ IATI elements are contained in files for each type of data """
    ORGANIZATION_MAIN_FILE = 100
    ORGANIZATION_NAMES_FILE = 110
    # Uncomment once needed
    # ORGANIZATION_BUDGET_FILE = 20
    # ORGANIZATION_EXPENDITURE_FILE = 30
    # ORGANIZATION_DOCUMENT_FILE = 40
    # ACTIVITY_MAIN_FILE = 50
    # ACTIVITY_BUDGET_FILE = 60
    # ACTIVITY_EXPENDITURE_FILE = 70
    # ACTIVITY_DOCUMENT_FILE = 80
    # ACTIVITY_LOCATION_FILE = 90
    # ACTIVITY_SECTOR_FILE = 100
    # ACTIVITY_PARTNER_FILE = 110
    # ACTIVITY_RESULT_FILE = 120
    # ACTIVITY_TRANSACTION_FILE = 130
    # ACTIVITY_POLICY_FILE = 140
